<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="TYSS-Chaithra" failures="1" tests="1" name="runnerClass.RunnerIO" time="13.444" errors="0" timestamp="2023-04-29T13:05:05 IST" skipped="0">
  <testcase classname="runnerClass.RunnerIO" name="runScenario" time="13.444">
    <failure message="expected [vtiger CRM 5 - Commercial Open Source CRM] but found [Vtiger CRM 5 - Commercial Open Source CRM]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [vtiger CRM 5 - Commercial Open Source CRM] but found [Vtiger CRM 5 - Commercial Open Source CRM]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at stepDefinitions.LoginTest.validate_for_home_page_title(LoginTest.java:56)
at âœ½.Validate for home Page title(file:///D:/MavenProjects/BDD.FrameworkPractice/./src/test/java/featureFiles/Login.feature:10)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runnerClass.RunnerIO -->
